### ISSUE TITLE
The [SharePoint link](https://kth-my.sharepoint.com/:f:/g/personal/yuningw_ug_kth_se/ErgO1ZWzoapCnHSJXIjdDyUB7TziV4P2cjzOYkUp2YKI_w?e=vQyak6) provided in the README file appears to be broken.

### ISSUE THREAD

**Issue by Yleo-9** [KTH-FlowAI/Physics-informed-neural-networks-for-solving-Reynolds-averaged-Navier-Stokes-equations#1]
I've noticed that the [SharePoint link](https://kth-my.sharepoint.com/:f:/g/personal/yuningw_ug_kth_se/ErgO1ZWzoapCnHSJXIjdDyUB7TziV4P2cjzOYkUp2YKI_w?e=vQyak6) provided in the README file seems to be broken. The error message received when attempting to access it is: "The link has expired. The link was set to expire after a certain time. Contact the person who shared the link with you." I hope this can be addressed, and I would like to thank you in advance for looking into this issue. Your assistance is greatly appreciated!

**Comment by Fantasy98** [comment]
Hi, 

Sorry for replying so late! I am putting the [new link](https://kth-my.sharepoint.com/:f:/g/personal/yuningw_ug_kth_se/El4GooUWpLxNgsp_77aSHRsBcL59rBA557E9yXLtanKNfw) here, please let me know if this works for you!

**Comment by Yleo-9** [comment]
<img width="549" alt="PixPin_2024-04-30_12-50-51" src="https://github.com/KTH-FlowAI/Physics-informed-neural-networks-for-solving-Reynolds-averaged-Navier-Stokes-equations/assets/70744145/53c0df7b-1642-4cc2-b531-362ee4ca11e2">
Thank you for your response and the new link. Unfortunately, the link still appears to be inactive when I attempt to access it. I'm wondering if this might be due to regional restrictions, as I am currently in Mainland China. (Email: liuyangestest@163.com)

**Comment by Fantasy98** [comment]
Hi, I have send an invitation to your email. Please check it and let me know if it works for you.

**Comment by Yleo-9** [comment]
Thank you very much! I have successfully downloaded the file through the invitation link you provided.
